### ISSUE TITLE
Visualization of correct baselines

### ISSUE THREAD

**Issue by diemmarkus** [Transkribus/TranskribusBaseLineEvaluationScheme#3]
this request is just important now (to understand the metric better).
the `-i` option is nice to see if GT/results are correct. An additional option that color codes tp,fp,fn lines would be nice if this is not too much work.

**Comment by TobiasGruening** [comment]
This is also integrated. If the tTV parameter is set (mentioned in the other issue) all tG-lines are visualized in blue all nG-lines also blue, but dashed. Same for hypo lines (only in red).
You'll get an image per mail :)
