### ISSUE TITLE
mvn install fails due to unresolved artifacts

### ISSUE THREAD

**Issue by wunderwuzzi1975** [Transkribus/TranskribusBaseLineEvaluationScheme#4]
Building TranskribusBaseLineEvaluationScheme 0.1.1 under Ubuntu 16.04 with Java 1.8.0_131 and Maven 3.3.9 fails due to unresolved artifacts org.primaresearch:PrimaDla:jar:2017-03-01, org.primaresearch:PrimaIo:jar:2017-03-01, org.primaresearch:PrimaMaths:jar:2017-03-01, and org.primaresearch:PrimaBasic:jar:2017-03-01.

See full log for more details:
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building TranskribusBaseLineEvaluationScheme 0.1.1
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom (8 KB at 9.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom (9 KB at 65.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom (30 KB at 198.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom (15 KB at 146.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar (29 KB at 232.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.3.2/maven-compiler-plugin-2.3.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.3.2/maven-compiler-plugin-2.3.2.pom (8 KB at 64.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/18/maven-plugins-18.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/18/maven-plugins-18.pom (13 KB at 122.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/16/maven-parent-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/16/maven-parent-16.pom (23 KB at 176.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/7/apache-7.pom (15 KB at 104.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.3.2/maven-compiler-plugin-2.3.2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/2.3.2/maven-compiler-plugin-2.3.2.jar (29 KB at 247.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.pom (5 KB at 43.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.17/surefire-2.17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.17/surefire-2.17.pom (17 KB at 134.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom (32 KB at 345.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom (14 KB at 150.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.jar (34 KB at 253.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom (6 KB at 59.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 KB at 47.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 KB at 91.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 KB at 77.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.jar (34 KB at 149.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.4.1/maven-assembly-plugin-2.4.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.4.1/maven-assembly-plugin-2.4.1.pom (17 KB at 75.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom (10 KB at 21.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/24/maven-parent-24.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/24/maven-parent-24.pom (37 KB at 275.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/14/apache-14.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/14/apache-14.pom (15 KB at 144.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.4.1/maven-assembly-plugin-2.4.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.4.1/maven-assembly-plugin-2.4.1.jar (212 KB at 965.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom (7 KB at 45.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar (33 KB at 198.4 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaDla/2017-03-01/PrimaDla-2017-03-01.pom
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaDla/2017-03-01/PrimaDla-2017-03-01.pom
[WARNING] The POM for org.primaresearch:PrimaDla:jar:2017-03-01 is missing, no dependency information available
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaIo/2017-03-01/PrimaIo-2017-03-01.pom
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaIo/2017-03-01/PrimaIo-2017-03-01.pom
[WARNING] The POM for org.primaresearch:PrimaIo:jar:2017-03-01 is missing, no dependency information available
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaMaths/2017-03-01/PrimaMaths-2017-03-01.pom
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaMaths/2017-03-01/PrimaMaths-2017-03-01.pom
[WARNING] The POM for org.primaresearch:PrimaMaths:jar:2017-03-01 is missing, no dependency information available
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.pom (11 KB at 8.3 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/apache/commons/commons-parent/37/commons-parent-37.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/apache/commons/commons-parent/37/commons-parent-37.pom (62 KB at 205.9 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/apache/apache/16/apache-16.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/apache/apache/16/apache-16.pom (16 KB at 61.1 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/knowm/xchart/xchart/3.1.0/xchart-3.1.0.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/knowm/xchart/xchart/3.1.0/xchart-3.1.0.pom (655 B at 3.2 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/knowm/xchart/xchart-parent/3.1.0/xchart-parent-3.1.0.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/knowm/xchart/xchart-parent/3.1.0/xchart-parent-3.1.0.pom (6 KB at 21.8 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/de/erichseifert/vectorgraphics2d/VectorGraphics2D/0.11/VectorGraphics2D-0.11.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/de/erichseifert/vectorgraphics2d/VectorGraphics2D/0.11/VectorGraphics2D-0.11.pom (3 KB at 10.4 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaBasic/2017-03-01/PrimaBasic-2017-03-01.pom
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaBasic/2017-03-01/PrimaBasic-2017-03-01.pom
[WARNING] The POM for org.primaresearch:PrimaBasic:jar:2017-03-01 is missing, no dependency information available
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/junit/junit/4.12/junit-4.12.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/junit/junit/4.12/junit-4.12.pom (24 KB at 99.2 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom (766 B at 3.4 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom (2 KB at 8.8 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaDla/2017-03-01/PrimaDla-2017-03-01.jar
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaIo/2017-03-01/PrimaIo-2017-03-01.jar
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaMaths/2017-03-01/PrimaMaths-2017-03-01.jar
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/knowm/xchart/xchart/3.1.0/xchart-3.1.0.jar
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar (52 KB at 145.8 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/de/erichseifert/vectorgraphics2d/VectorGraphics2D/0.11/VectorGraphics2D-0.11.jar
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/knowm/xchart/xchart/3.1.0/xchart-3.1.0.jar (175 KB at 395.3 KB/sec)
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/primaresearch/PrimaBasic/2017-03-01/PrimaBasic-2017-03-01.jar
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/junit/junit/4.12/junit-4.12.jar
Downloading: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/de/erichseifert/vectorgraphics2d/VectorGraphics2D/0.11/VectorGraphics2D-0.11.jar (91 KB at 126.2 KB/sec)
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar (44 KB at 45.6 KB/sec)
Downloaded: http://dbis-halvar.uibk.ac.at/artifactory/libs-release/junit/junit/4.12/junit-4.12.jar (308 KB at 277.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaDla/2017-03-01/PrimaDla-2017-03-01.jar
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaIo/2017-03-01/PrimaIo-2017-03-01.jar
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaMaths/2017-03-01/PrimaMaths-2017-03-01.jar
Downloading: https://repo.maven.apache.org/maven2/org/primaresearch/PrimaBasic/2017-03-01/PrimaBasic-2017-03-01.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.355 s
[INFO] Finished at: 2017-05-19T23:24:35+02:00
[INFO] Final Memory: 12M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TranskribusBaseLineEvaluationScheme: Could not resolve dependencies for project eu.transkribus:TranskribusBaseLineEvaluationScheme:jar:0.1.1: The following artifacts could not be resolved: org.primaresearch:PrimaDla:jar:2017-03-01, org.primaresearch:PrimaIo:jar:2017-03-01, org.primaresearch:PrimaMaths:jar:2017-03-01, org.primaresearch:PrimaBasic:jar:2017-03-01: Could not find artifact org.primaresearch:PrimaDla:jar:2017-03-01 in dea-artifactory (http://dbis-halvar.uibk.ac.at/artifactory/libs-release/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jkloe** [comment]
The reason is that the newest primaresearch tools (https://github.com/PRImA-Research-Lab/prima-core-libs)  are used in the pom.xml (see commit 033ccb4d5904feb3fa9b6f697774c6ff5de3d5e6) - version string is 2017-03-01 instead of 15-10-2013. Those versions are not deployed on our artifactory at http://dbis-halvar.uibk.ac.at/artifactory.
The newest versions of the tools are based on the new PAGE format from 2016 but Transkribus is based on the old version from 2013 and I am not sure if 2016 is downwards compatible.
@TobiasGruening Do you need the new versions of the libraries and if yes, please send them to me so that I can deploy them on the artifactoy.

**Comment by TobiasGruening** [comment]
We are working on a solution. Hopefully it will be fixed soon!

**Comment by lunactic** [comment]
great to hear! I ran into the same problem recently so good to know there will be a fix soon :)

**Comment by TobiasGruening** [comment]
It should be fixed now.
Thx @jkloe   !

**Comment by wunderwuzzi1975** [comment]
Building TranskribusBaseLineEvaluationScheme 0.1.2 under Ubuntu 16.04 with Java 1.8.0_131 and Maven 3.3.9 was successful. Thank you very much for fixing! Closing issue.

**Comment by TobiasGruening** [comment]
There was a bug in the first version of the dependencies.
This is fixed now.
The version build on your system should work properly now.
So please update the dependencies.
