### ISSUE TITLE
NullPointerException when evaluating a reco file that does not contain a baseline

### ISSUE THREAD

**Issue by wunderwuzzi1975** [Transkribus/TranskribusBaseLineEvaluationScheme#5]
TranskribusBaseLineEvaluationScheme 0.1.1 crashes with a NullPointerException under Ubuntu 16.04 with Java 1.8.0_131 during evaluation of a reco file that does not contain any baselines at all (= empty text file) against a truth file (= valid PAGE xml file). I have attached both files as zip-file to this issue.

Input: java -jar TranskribusBaseLineEvaluationScheme-0.1.1-jar-with-dependencies.jar HS22b_73_object_19845.xml HS22b_73_object_19845.txt

Output: Exception in thread "main" java.lang.NullPointerException at eu.transkribus.baselineevaluationscheme.Metric_BL_run.run(Metric_BL_run.java:204) at eu.transkribus.baselineevaluationscheme.Metric_BL_run.main(Metric_BL_run.java:487)

[HS22b_73_object_19845.zip](https://github.com/Transkribus/TranskribusBaseLineEvaluationScheme/files/1035587/HS22b_73_object_19845.zip)

**Comment by TobiasGruening** [comment]
Thx for the issue.
Fixed with commit a455d09c3d669b5138db8adb2d697ee9f7235980 
TranskribusBaseLineEvaluationScheme-0.1.2-jar-with-dependencies.jar including this bugfix is also uploaded.

**Comment by wunderwuzzi1975** [comment]
Works like a charm. Thank you very much for fixing! Closing issue.
